### ISSUE TITLE
Check test coverage and provide more tests where applicable

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-core#315]
@jasinai you already checked this, please report your results and remove your assignment from this issue.

@Qabel/developer please act accordingly.

**Comment by thechauffeur** [comment]
Tests like the MultiPartCrypto test are definitely a good idea. This test should also be patched so it looks more like a module is actually involved there -- @Gottox knows what I mean.

**Comment by jan-schreib** [comment]
After fighting with my IDE for a couple of hours I finally got the statistics:

Types|Percentage
--------|--------------
Class coverage: |    69
Method coverage:| 88
Line coverage:     | 80

That is pretty good. We could bring it to 100%, but its useless to test trivial mutators and accessors.
For example there are not tests in for our written exceptions, IMHO none are needed.

I discovered a few functions that could be testet, but since there is no logic in them I doubt that a unit test is needed. That would be a case for compenent or system tests.

**Comment by thechauffeur** [comment]
Having useful tests with 80% coverage is far better than stupid tests with 100% coverage.

**Comment by thechauffeur** [comment]
@jasinai please manually look into our tests and where we missing some or where we need better tests. You should create issues for each occurrence so that we know where to enhance our tests.

**Comment by thechauffeur** [comment]
Our tests regarding the core are sufficient now.
