### ISSUE TITLE
CryptoUtils cannot encrypt small files

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-core#401]
If I try to encrypt a file that is very small (1 byte for example), gcmCypher.update in CryptoUtils.java:192 returns null which then causes the .write() to fail with a NullPointerException.

**Comment by L-Henke** [comment]
I can confirm that the minimal input size in 16 bytes. This seems to be a bug in bouncy castle. The GCM mode itself does not limit the input size. According to the [spec](http://csrc.nist.gov/groups/ST/toolkit/BCM/documents/proposedmodes/gcm/gcm-spec.pdf) any plaintext between 0 and 2^29 -256 bits is a valid input.

If I directly call ```gcmCipher.doFinal()``` with 15 bytes input I get the following error message: ```Input too short for block cipher. Input length was 31```. I guess 31 bytes are 16 bytes IV + 15 bytes plaintext.

So I would say this is a bug in Bouncycasle, since Galois/**Counter** Mode is not really a block cipher.

The question is how do we want to handle this. Document the minimal input size of 16 bytes and throw an exception if input size is too small?

**Comment by roeslpa** [comment]
I cannot reproduce this bug. Tested it with one character = 1 Byte and it worked well. Maybe the used Spongycastle version fixes it?! (see shortFileEncryption branch)
I would suggest to close this issue.

**Comment by roeslpa** [comment]
@audax @L-Henke can one of you confirm this/close this issue?

**Comment by jmt85** [comment]
can you please check this

**Comment by audax** [comment]
It doesn't happen anymore, I can easily encrypt 0 byte files.
