### ISSUE TITLE
sync Conflict

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-core#488]
A conflict occurs when a user sync the same file from more than one device at the same time.   

normal
1. doc 		↔ 	 doc    		✓ 

conflict
2. doc¹ 		→ 	doc²	 	        ✗ 
--> renaming into doc_$conf²	

solution
3. doc¹		→	doc¹		        ✓	
doc_$conf²	←	doc_$conf²	✓

**Comment by julianseeger** [comment]
IIRC the point here was that we don't want consecutive saves of a document to produce an infinite amount of conflict-files while - at the same time - we don't want to rename a file the user is "working on" because it would lead to the editor-application to probably overwrite the not-renamed file and don't know that it has been renamed.
Don't know how we solved the "working on" thing but if consecutive saves shouldn't lead to more and more conflict files, we would have to rename the first file that was there. So
```GHERKIN
Given device A uploads file 'doc' (content A1)
And device B uploads file 'doc' (content B1)
When device B uploads file 'doc' (content B2)
Then there is a file 'doc_$conflict' (content A1)
And a file 'doc' (content B2)
```

=> only 1 conflict file and the content A1 of device A is never lost, no matter how often B saves.
If A uploads again, we have 2 conflict files, archiving A1 and B2.

**Comment by julianseeger** [comment]
`newFile` := file that is the program is about to insert into the dm
`oldFile` := file that was there when the insert of `newFile` was initiated
`currentFile` := file that is "currently" in the DM
newFile.name == oldFile.name == currentFile.name

@audax @thechauffeur is it valid to state that every time a conflict on DM level occurs (1 newFile has been changed/created but the oldFile has changed in the meantime) it is a conflict when `newFile.deviceId != currentFile.deviceId` but it is just a normal overwrite operation without a conflict file if `newFile.deviceId == currentFile.deviceId` ?
That way we could ensure that no matter what happens, two files from the same device never conflict.
