### ISSUE TITLE
Conflict By Same Name

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-core#492]
Folder a/b/c → 	…	← a/b/c
create data clutter

Solution:
File hashes into dm 
size & mtime for prediction

**Comment by julianseeger** [comment]
In human words IIRC:
The folders won't conflict because we defined a CREATE_DIRECTORY action as non conflicting (because it is ignored the second time).
Before we apply #488 to resolve file conflicts, we compare the hashes stored in the dm. And if they match, we assume the files are equal and no conflict resolution is required.

And I've forgotten what we do with size&mtime... maybe we just use them locally to predict when the hash might have to be recalculated...

**Comment by audax** [comment]
Sounds right…

I think we compar filesize + hash to be sure, instead of just the hash.

**Comment by julianseeger** [comment]
Did anyone check that this works for the desktop client / sync? Like integration...
If not, please check or create a new ticket .. or reopen this one?

**Comment by audax** [comment]
@julianseeger made a new ticket for it to test this explicitly with the sync
